apiVersion: apps/v1
kind: Deployment
metadata:
  name: depapp
  labels:
    app: reverse-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reverse-app
  template:
    metadata:
      labels:
        app: reverse-app
    spec:
      containers:
      - name: reverse-app-c
        image: almoglevig/reverseurl:1.0
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svcapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingress-nginx
  rules:
  - http:
      paths:
      - path: /reverse
        pathType: Prefix
        backend:
          service:
            name: svcapp
            port:
              number: 80
